// https://stackoverflow.com/questions/61964265/getting-error-this-document-requires-trustedhtml-assignment-in-chrome
escapeHTMLPolicy = trustedTypes.createPolicy("forceInner", {
  createHTML: (to_escape) => to_escape
});

moveCursorToEndOfEditor = (editor) => {
  editor.focus();
  window.getSelection().selectAllChildren(editor);
  window.getSelection().collapseToEnd();
}

getEmojiDescription = (emojiHtml) => {
  // TODO detect emoji and use common emojis
  // https://stackoverflow.com/questions/6639770/how-do-i-get-the-unicode-hex-representation-of-a-symbol-out-of-the-html-using-ja
  // https://emojipedia.org/pt/pessoas/
  const attr = 'data-emoji';
  const regex = new RegExp(`${attr}="(.*?)"`);
  const match = emojiHtml[0].match(regex);
  const value = match && match[1];

  // maybe this should be moved to another file since it'll be a huge list
  const emojiDescriptions = {
    // https://emojipedia.org/pt/pessoas/
    "😀": "rosto risonho",
    "😃": "rosto risonho com olhos bem abertos",
    "😄": "rosto risonho com olhos sorridentes",
    "😁": "rosto contente com olhos sorridentes",
    "😆": "rosto risonho com olhos semicerrados",
    "😅": "rosto risonho com gota de suor",
    "🤣": "rolando no chão de rir",
    "😂": "rosto chorando de rir",
    "🙂": "rosto levemente sorridente",
    "🙃": "rosto de cabeça para baixo",
    "🫠": "cara a derreter",
    "😉": "rosto com olho piscando",
    "😊": "rosto sorridente com olhos sorridentes",
    "😇": "rosto sorridente com auréola",
    "🥰": "rosto sorridente com 3 corações",
    "😍": "rosto sorridente com olhos de coração",
    "🤩": "rosto com olhar maravilhado",
    "😘": "rosto mandando um beijo",
    "😗": "rosto beijando",
    "☺️": "rosto sorridente",
    "😚": "rosto beijando com olhos fechados",
    "😙": "rosto beijando com olhos sorridentes",
    "🥲": "rosto sorridente com lágrima",
    "😋": "rosto saboreando comida",
    "😛": "rosto mostrando a língua",
    "😜": "rosto piscando e com língua para fora",
    "🤪": "rosto bizarro",
    "😝": "rosto com olhos semicerrados e língua para fora",
    "🤑": "rosto com cifrões",
    "🤗": "rosto abraçando",
    "🤭": "rosto com a mão sobre a boca",
    "🫢": "cara com os olhos abertos e a mão na boca",
    "🫣": "cara com olho a espreitar",
    "🤫": "rosto fazendo sinal de silêncio",
    "🤔": "rosto pensativo",
    "🫡": "cara de saudação",
    "🤐": "rosto com boca de zíper",
    "🤨": "rosto com sobrancelha levantada",
    "😐": "rosto neutro",
    "😑": "rosto inexpressivo",
    "😶": "rosto sem boca",
    "🫥": "cara com linha tracejada",
    "😶‍🌫️": "rosto nas nuvens",
    "😏": "rosto com sorriso maroto",
    "😒": "rosto aborrecido",
    "🙄": "rosto com olhos revirados",
    "😬": "rosto expressando desagrado",
    "😮‍💨": "rosto exalando",
    "🤥": "rosto de mentiroso",
    "😌": "rosto aliviado",
    "😔": "rosto deprimido",
    "😪": "rosto sonolento",
    "🤤": "rosto babando",
    "😴": "rosto dormindo",
    "😷": "rosto com máscara médica",
    "🤒": "rosto com termômetro",
    "🤕": "rosto com atadura na cabeça",
    "🤢": "rosto nauseado",
    "🤮": "rosto vomitando",
    "🤧": "rosto espirrando",
    "🥵": "rosto fervendo de calor",
    "🥶": "rosto gelado",
    "🥴": "rosto embriagado",
    "😵": "rosto atordoado",
    "😵‍💫": "rosto com olhos em espiral",
    "🤯": "cabeça explodindo",
    "🤠": "rosto com chapéu de caubói",
    "🥳": "rosto festivo",
    "🥸": "rosto disfarçado",
    "😎": "rosto sorridente com óculos escuros",
    "🤓": "rosto de nerd",
    "🧐": "rosto com monóculo",
    "😕": "rosto confuso",
    "🫤": "cara com boca na diagonal",
    "😟": "rosto preocupado",
    "🙁": "rosto meio triste",
    "☹️": "rosto descontente",
    "😮": "rosto com boca aberta",
    "😯": "rosto surpreso",
    "😲": "rosto espantado",
    "😳": "rosto ruborizado",
    "🥺": "rosto implorando",
    "🥹": "cara a conter as lágrimas",
    "😦": "rosto franzido com boca aberta",
    "😧": "rosto angustiado",
    "😨": "rosto amedrontado",
    "😰": "rosto ansioso com gota de suor",
    "😥": "rosto triste, mas aliviado",
    "😢": "rosto chorando",
    "😭": "rosto chorando aos berros",
    "😱": "rosto gritando de medo",
    "😖": "rosto perplexo",
    "😣": "rosto perseverante",
    "😞": "rosto desapontado",
    "😓": "rosto cabisbaixo com gota de suor",
    "😩": "rosto desolado",
    "😫": "rosto cansado",
    "🥱": "rosto bocejando",
    "😤": "rosto soltando vapor pelo nariz",
    "😡": "rosto furioso",
    "😠": "rosto zangado",
    "🤬": "rosto com símbolos na boca",
    "😈": "rosto sorridente com chifres",
    "👿": "rosto zangado com chifres",
    "💀": "caveira",
    "☠️": "caveira e ossos cruzados",
    "💩": "cocô",
    "🤡": "rosto de palhaço",
    "👹": "ogro",
    "👺": "duende japonês",
    "👻": "fantasma",
    "👽": "alienígena",
    "👾": "monstro alienígena",
    "🤖": "rosto de robô",
    "😺": "rosto de gato sorrindo",
    "😸": "rosto de gato sorrindo com olhos sorridentes",
    "😹": "rosto de gato com lágrimas de alegria",
    "😻": "rosto de gato sorridente com olhos de coração",
    "😼": "rosto de gato com sorriso irônico",
    "😽": "rosto de gato mandando um beijo",
    "🙀": "rosto de gato desolado",
    "😿": "rosto de gato chorando",
    "😾": "rosto de gato mal-humorado",
    "💋": "marca de beijo",
    "👋": "mão acenando",
    "🤚": "dorso da mão levantado",
    "🖐️": "mão aberta com os dedos separados",
    "✋": "mão levantada",
    "🖖": "saudação vulcana",
    "🫱": "mão para a direita",
    "🫲": "mão para a esquerda",
    "🫳": "palma da mão virada para baixo",
    "🫴": "palma da mão virada para cima",
    "👌": "sinal de ok",
    "🤌": "dedos comprimidos",
    "🤏": "mão beliscando",
    "✌️": "mão em v de vitória",
    "🤞": "dedos cruzados",
    "🫰": "mão com o dedo indicador e o polegar cruzados",
    "🤟": "gesto de \"te amo\"",
    "🤘": "saudação do rock",
    "🤙": "sinal \"me liga\"",
    "👈": "dorso da mão com dedo indicador apontando para a esquerda",
    "👉": "dorso da mão com dedo indicador apontando para a direita",
    "👆": "dorso da mão com dedo indicador apontando para cima",
    "🖕": "dedo do meio",
    "👇": "dorso da mão com dedo indicador apontando para baixo",
    "☝️": "indicador apontando para cima",
    "🫵": "dedo indicador a apontar ao visor",
    "👍": "polegar para cima",
    "👎": "polegar para baixo",
    "✊": "punho levantado",
    "👊": "soco",
    "🤛": "punho esquerdo",
    "🤜": "punho direito",
    "👏": "mãos aplaudindo",
    "🙌": "mãos para cima",
    "🫶": "mãos em coração",
    "👐": "mãos abertas",
    "🤲": "palmas unidas para cima",
    "🤝": "aperto de mãos",
    "🙏": "mãos juntas",
    "✍️": "escrevendo à mão",
    "💅": "esmalte de unha",
    "🤳": "selfie",
    "💪": "bíceps",
    "🦾": "braço mecânico",
    "🦿": "perna mecânica",
    "🦵": "perna",
    "🦶": "pé",
    "👂": "orelha",
    "🦻": "ouvido com aparelho auditivo",
    "👃": "nariz",
    "🧠": "cérebro",
    "🫀": "coração humano",
    "🫁": "pulmões",
    "🦷": "dente",
    "🦴": "osso",
    "👀": "olhos",
    "👁️": "olho",
    "👅": "língua",
    "👄": "boca",
    "🫦": "morder o lábio",
    "👶": "bebê",
    "🧒": "criança",
    "👦": "menino",
    "👧": "menina",
    "🧑": "pessoa",
    "👱": "pessoa: cabelo louro",
    "👨": "homem",
    "🧔": "homem: barba",
    "👨‍🦰": "homem: cabelo vermelho",
    "👨‍🦱": "homem: cabelo cacheado",
    "👨‍🦳": "homem: cabelo branco",
    "👨‍🦲": "homem: careca",
    "👩": "mulher",
    "👩‍🦰": "mulher: cabelo vermelho",
    "🧑‍🦰": "pessoa: cabelo vermelho",
    "👩‍🦱": "mulher: cabelo cacheado",
    "🧑‍🦱": "pessoa: cabelo cacheado",
    "👩‍🦳": "mulher: cabelo branco",
    "🧑‍🦳": "pessoa: cabelo branco",
    "👩‍🦲": "mulher: careca",
    "🧑‍🦲": "pessoa: careca",
    "👱‍♀️": "mulher: cabelo loiro",
    "👱‍♂️": "homem: cabelo loiro",
    "🧓": "idoso",
    "👴": "homem idoso",
    "👵": "idosa",
    "🙍": "franzindo a sobrancelha",
    "🙍‍♂️": "homem franzindo a sobrancelha",
    "🙍‍♀️": "mulher franzindo a sobrancelha",
    "🙎": "pessoa fazendo bico",
    "🙎‍♂️": "homem fazendo bico",
    "🙎‍♀️": "mulher fazendo bico",
    "🙅": "pessoa fazendo gesto de “não”",
    "🙅‍♂️": "homem fazendo gesto de “não”",
    "🙅‍♀️": "mulher fazendo gesto de “não”",
    "🙆": "pessoa fazendo gesto de “ok”",
    "🙆‍♂️": "homem fazendo gesto de “ok”",
    "🙆‍♀️": "mulher fazendo gesto de “ok”",
    "💁": "pessoa com a palma virada para cima",
    "💁‍♂️": "homem com a palma virada para cima",
    "💁‍♀️": "mulher com a palma virada para cima",
    "🙋": "pessoa levantando a mão",
    "🙋‍♂️": "homem levantando a mão",
    "🙋‍♀️": "mulher levantando a mão",
    "🧏": "pessoa surda",
    "🧏‍♂️": "homem surdo",
    "🧏‍♀️": "mulher surda",
    "🙇": "pessoa fazendo reverência",
    "🙇‍♂️": "homem fazendo reverência",
    "🙇‍♀️": "mulher fazendo reverência",
    "🤦": "pessoa decepcionada",
    "🤦‍♂️": "homem decepcionado",
    "🤦‍♀️": "mulher decepcionada",
    "🤷": "pessoa dando de ombros",
    "🤷‍♂️": "homem dando de ombros",
    "🤷‍♀️": "mulher dando de ombros",
    "🧑‍⚕️": "profissional de saúde",
    "👨‍⚕️": "homem profissional da saúde",
    "👩‍⚕️": "mulher profissional da saúde",
    "🧑‍🎓": "aluno",
    "👨‍🎓": "estudante",
    "👩‍🎓": "aluna",
    "🧑‍🏫": "professora na escola",
    "👨‍🏫": "professor",
    "👩‍🏫": "professora",
    "🧑‍⚖️": "juiz no tribunal",
    "👨‍⚖️": "juiz",
    "👩‍⚖️": "juíza",
    "🧑‍🌾": "agricultor",
    "👨‍🌾": "fazendeiro",
    "👩‍🌾": "fazendeira",
    "🧑‍🍳": "chef de cozinha",
    "👨‍🍳": "cozinheiro",
    "👩‍🍳": "cozinheira",
    "🧑‍🔧": "mecânico trabalhando",
    "👨‍🔧": "mecânico",
    "👩‍🔧": "mecânica",
    "🧑‍🏭": "funcionário de fábrica",
    "👨‍🏭": "operário",
    "👩‍🏭": "operária",
    "🧑‍💼": "trabalhador de escritório",
    "👨‍💼": "funcionário de escritório",
    "👩‍💼": "funcionária de escritório",
    "🧑‍🔬": "cientista",
    "👨‍🔬": "cientista homem",
    "👩‍🔬": "cientista mulher",
    "🧑‍💻": "programador",
    "👨‍💻": "tecnólogo",
    "👩‍💻": "tecnóloga",
    "🧑‍🎤": "cantor",
    "👨‍🎤": "cantor homem",
    "👩‍🎤": "cantora",
    "🧑‍🎨": "artista",
    "👨‍🎨": "artista plástico",
    "👩‍🎨": "artista plástica",
    "🧑‍✈️": "piloto",
    "👨‍✈️": "piloto de avião homem",
    "👩‍✈️": "piloto de avião mulher",
    "🧑‍🚀": "astronauta",
    "👨‍🚀": "astronauta homem",
    "👩‍🚀": "astronauta mulher",
    "🧑‍🚒": "bombeiro",
    "👨‍🚒": "bombeiro homem",
    "👩‍🚒": "bombeira",
    "👮": "policial",
    "👮‍♂️": "policial homem",
    "👮‍♀️": "policial mulher",
    "🕵️": "detetive",
    "🕵️‍♂️": "detetive homem",
    "🕵️‍♀️": "detetive mulher",
    "💂": "guarda",
    "💂‍♂️": "guarda homem",
    "💂‍♀️": "guarda mulher",
    "🥷": "ninja",
    "👷": "trabalhador de construção civil",
    "👷‍♂️": "pedreiro",
    "👷‍♀️": "pedreira",
    "🫅": "pessoa com coroa",
    "🤴": "príncipe",
    "👸": "princesa",
    "👳": "pessoa com turbante",
    "👳‍♂️": "homem com turbante",
    "👳‍♀️": "mulher com turbante",
    "👲": "homem de boné",
    "🧕": "mulher com véu",
    "🤵": "pessoa de smoking",
    "🤵‍♂️": "homem de smoking",
    "🤵‍♀️": "mulher de smoking",
    "👰": "noiva",
    "👰‍♂️": "noivo com véu",
    "👰‍♀️": "noiva com véu",
    "🤰": "grávida",
    "🫃": "homem grávido",
    "🫄": "pessoa grávida",
    "🤱": "amamentando",
    "👩‍🍼": "mulher alimentando bebê",
    "👨‍🍼": "homem alimentando bebê",
    "🧑‍🍼": "pessoa alimentando bebê",
    "👼": "bebê anjo",
    "🎅": "papai noel",
    "🤶": "mamãe noel",
    "🧑‍🎄": "noel",
    "🦸": "super-herói",
    "🦸‍♂️": "homem super-herói",
    "🦸‍♀️": "super-heroína",
    "🦹": "supervilão",
    "🦹‍♂️": "homem supervilão",
    "🦹‍♀️": "supervilã",
    "🧙": "mago",
    "🧙‍♂️": "homem mago",
    "🧙‍♀️": "maga",
    "🧚": "fada",
    "🧚‍♂️": "homem fada",
    "🧚‍♀️": "mulher fada",
    "🧛": "vampiro",
    "🧛‍♂️": "homem vampiro",
    "🧛‍♀️": "mulher vampira",
    "🧜": "pessoa sereia",
    "🧜‍♂️": "sereio",
    "🧜‍♀️": "sereia",
    "🧝": "elfo",
    "🧝‍♂️": "elfo homem",
    "🧝‍♀️": "elfa",
    "🧞": "gênio",
    "🧞‍♂️": "homem gênio",
    "🧞‍♀️": "mulher gênio",
    "🧟": "zumbi",
    "🧟‍♂️": "homem zumbi",
    "🧟‍♀️": "mulher zumbi",
    "🧌": "duende",
    "💆": "pessoa recebendo massagem facial",
    "💆‍♂️": "homem recebendo massagem facial",
    "💆‍♀️": "mulher recebendo massagem facial",
    "💇": "pessoa cortando o cabelo",
    "💇‍♂️": "homem cortando o cabelo",
    "💇‍♀️": "mulher cortando o cabelo",
    "🚶": "pessoa andando",
    "🚶‍♂️": "homem andando",
    "🚶‍♀️": "mulher andando",
    "🧍": "pessoa em pé",
    "🧍‍♂️": "homem em pé",
    "🧍‍♀️": "mulher em pé",
    "🧎": "pessoa ajoelhando",
    "🧎‍♂️": "homem ajoelhando",
    "🧎‍♀️": "mulher ajoelhando",
    "🧑‍🦯": "pessoa com bengala para cego",
    "👨‍🦯": "homem com bengala para cego",
    "👩‍🦯": "mulher com bengala para cego",
    "🧑‍🦼": "pessoa em cadeira de rodas motorizada",
    "👨‍🦼": "homem em cadeira de rodas motorizada",
    "👩‍🦼": "mulher em cadeira de rodas motorizada",
    "🧑‍🦽": "pessoa em cadeira de rodas manual",
    "👨‍🦽": "homem em cadeira de rodas manual",
    "👩‍🦽": "mulher em cadeira de rodas manual",
    "🏃": "pessoa correndo",
    "🏃‍♂️": "homem correndo",
    "🏃‍♀️": "mulher correndo",
    "💃": "mulher dançando",
    "🕺": "homem dançando",
    "🕴️": "pessoa de terno levitando",
    "👯": "pessoas com orelhas de coelho",
    "👯‍♂️": "homens com orelhas de coelho",
    "👯‍♀️": "mulheres com orelhas de coelho",
    "🧖": "pessoa na sauna",
    "🧖‍♂️": "homem na sauna",
    "🧖‍♀️": "mulher na sauna",
    "🧘": "pessoa na posição de lótus",
    "🧑‍🤝‍🧑": "pessoas de mãos dadas",
    "👭": "duas mulheres de mãos dadas",
    "👫": "homem e mulher de mãos dadas",
    "👬": "dois homens de mãos dadas",
    "💏": "beijo",
    "👩‍❤️‍💋‍👨": "beijo: mulher, homem",
    "👨‍❤️‍💋‍👨": "beijo: homem, homem",
    "👩‍❤️‍💋‍👩": "beijo: mulher, mulher",
    "💑": "casal apaixonado",
    "👩‍❤️‍👨": "casal apaixonado: mulher, homem",
    "👨‍❤️‍👨": "casal apaixonado: homem, homem",
    "👩‍❤️‍👩": "casal apaixonado: mulher, mulher",
    "👪": "família",
    "👨‍👩‍👦": "família: homem, mulher, menino",
    "👨‍👩‍👧": "família: homem, mulher, menina",
    "👨‍👩‍👧‍👦": "família: homem, mulher, menina, menino",
    "👨‍👩‍👦‍👦": "família: homem, mulher, menino, menino",
    "👨‍👩‍👧‍👧": "família: homem, mulher, menina, menina",
    "👨‍👨‍👦": "família: homem, homem, menino",
    "👨‍👨‍👧": "família: homem, homem, menina",
    "👨‍👨‍👧‍👦": "família: homem, homem, menina, menino",
    "👨‍👨‍👦‍👦": "família: homem, homem, menino, menino",
    "👨‍👨‍👧‍👧": "família: homem, homem, menina, menina",
    "👩‍👩‍👦": "família: mulher, mulher, menino",
    "👩‍👩‍👧": "família: mulher, mulher, menina",
    "👩‍👩‍👧‍👦": "família: mulher, mulher, menina, menino",
    "👩‍👩‍👦‍👦": "família: mulher, mulher, menino, menino",
    "👩‍👩‍👧‍👧": "família: mulher, mulher, menina, menina",
    "👨‍👦": "família: homem, menino",
    "👨‍👦‍👦": "família: homem, menino, menino",
    "👨‍👧": "família: homem, menina",
    "👨‍👧‍👦": "família: homem, menina, menino",
    "👨‍👧‍👧": "família: homem, menina, menina",
    "👩‍👦": "família: mulher, menino",
    "👩‍👦‍👦": "família: mulher, menino, menino",
    "👩‍👧": "família: mulher, menina",
    "👩‍👧‍👦": "família: mulher, menina, menino",
    "👩‍👧‍👧": "família: mulher, menina, menina",
    "🗣️": "silhueta falando",
    "👤": "silhueta de busto",
    "👥": "silhueta de bustos",
    "🫂": "pessoas se abraçando",
    "👣": "pegadas",
    "🧳": "mala",
    "🌂": "guarda-chuva fechado",
    "☂️": "guarda-chuva",
    "🎃": "abóbora de halloween",
    "🧵": "carretel",
    "🧶": "novelo",
    "👓": "óculos",
    "🕶️": "óculos escuros",
    "🥽": "óculos de proteção",
    "🥼": "jaleco",
    "🦺": "colete salva-vidas",
    "👔": "gravata",
    "👕": "camiseta",
    "👖": "jeans",
    "🧣": "cachecol",
    "🧤": "luvas",
    "🧥": "casaco",
    "🧦": "meias",
    "👗": "vestido",
    "👘": "quimono",
    "🥻": "sari",
    "🩱": "maiô",
    "🩲": "cueca",
    "🩳": "shorts",
    "👙": "biquíni",
    "👚": "roupas femininas",
    "👛": "bolsinha",
    "👜": "bolsa de mão",
    "👝": "bolsa pequena",
    "🎒": "mochila",
    "🩴": "chinelo",
    "👞": "sapato masculino",
    "👟": "tênis de corrida",
    "🥾": "bota de trekking",
    "🥿": "sapatilha",
    "👠": "sapato de salto alto",
    "👡": "sandália feminina",
    "🩰": "sapatilha de balé",
    "👢": "bota feminina",
    "👑": "coroa",
    "👒": "chapéu feminino",
    "🎩": "cartola",
    "🎓": "chapéu de formatura",
    "🧢": "boné",
    "🪖": "capacete militar",
    "⛑️": "capacacete de socorrista",
    "💄": "batom",
    "💍": "anel",
    "💼": "maleta",
    "🩸": "gota de sangue",

    // https://emojipedia.org/pt/animais-e-natureza/
    "🙈": "macaco que não vê nada",
    "🙉": "macaco que não ouve nada",
    "🙊": "macaco que não fala nada",
    "💥": "colisão",
    "💫": "zonzo",
    "💦": "pingos de suor",
    "💨": "rapidez",
    "🐵": "rosto de macaco",
    "🐒": "macaco",
    "🦍": "gorila",
    "🦧": "orangotango",
    "🐶": "rosto de cachorro",
    "🐕": "cachorro",
    "🦮": "cão-guia",
    "🐕‍🦺": "cão de serviço",
    "🐩": "poodle",
    "🐺": "rosto de lobo",
    "🦊": "rosto de raposa",
    "🦝": "guaxinim",
    "🐱": "rosto de gato",
    "🐈": "gato",
    "🐈‍⬛": "gato preto",
    "🦁": "rosto de leão",
    "🐯": "rosto de tigre",
    "🐅": "tigre",
    "🐆": "leopardo",
    "🐴": "rosto de cavalo",
    "🐎": "cavalo",
    "🦄": "rosto de unicórnio",
    "🦓": "zebra",
    "🦌": "cervo",
    "🦬": "bisão",
    "🐮": "rosto de vaca",
    "🐂": "boi",
    "🐃": "búfalo-asiático",
    "🐄": "vaca",
    "🐷": "rosto de porco",
    "🐖": "porco",
    "🐗": "javali",
    "🐽": "nariz de porco",
    "🐏": "carneiro",
    "🐑": "ovelha",
    "🐐": "cabra",
    "🐪": "camelo",
    "🐫": "camelo com duas corcovas",
    "🦙": "lhama",
    "🦒": "girafa",
    "🐘": "elefante",
    "🦣": "mamute",
    "🦏": "rinoceronte",
    "🦛": "hipopótamo",
    "🐭": "rosto de camundongo",
    "🐁": "camundongo",
    "🐀": "rato",
    "🐹": "rosto de hamster",
    "🐰": "rosto de coelho",
    "🐇": "coelho",
    "🐿️": "esquilo",
    "🦫": "castor",
    "🦔": "porco-espinho",
    "🦇": "morcego",
    "🐻": "rosto de urso",
    "🐻‍❄️": "urso polar",
    "🐨": "coala",
    "🐼": "rosto de panda",
    "🦥": "preguiça",
    "🦦": "lontra",
    "🦨": "gambá",
    "🦘": "canguru",
    "🦡": "texugo",
    "🐾": "patas",
    "🦃": "peru",
    "🐔": "galinha",
    "🐓": "galo",
    "🐣": "pintinho chocando",
    "🐤": "pintinho de perfil",
    "🐥": "pintinho de frente",
    "🐦": "pássaro",
    "🐧": "pinguim",
    "🕊️": "pomba branca",
    "🦅": "águia",
    "🦆": "pato",
    "🦢": "cisne",
    "🦉": "coruja",
    "🦤": "dodô",
    "🪶": "pena",
    "🦩": "flamingo",
    "🦚": "pavão",
    "🦜": "papagaio",
    "🐸": "sapo",
    "🐊": "crocodilo",
    "🐢": "tartaruga",
    "🦎": "lagartixa",
    "🐍": "cobra",
    "🐲": "rosto de dragão",
    "🐉": "dragão",
    "🦕": "saurópode",
    "🦖": "tiranossauro rex",
    "🐳": "baleia esguichando água",
    "🐋": "baleia",
    "🐬": "golfinho",
    "🦭": "foca",
    "🐟": "peixe",
    "🐠": "peixe tropical",
    "🐡": "baiacu",
    "🦈": "tubarão",
    "🐙": "polvo",
    "🐚": "caramujo",
    "🪸": "coral",
    "🐌": "caracol",
    "🦋": "borboleta",
    "🐛": "inseto",
    "🐜": "formiga",
    "🐝": "abelha",
    "🪲": "besouro",
    "🐞": "joaninha",
    "🦗": "grilo",
    "🪳": "barata",
    "🕷️": "aranha",
    "🕸️": "teia de aranha",
    "🦂": "escorpião",
    "🦟": "mosquito",
    "🪰": "mosca",
    "🪱": "minhoca",
    "🦠": "micróbio",
    "💐": "buquê",
    "🌸": "flor de cerejeira",
    "💮": "flor branca",
    "🪷": "flor de lotus",
    "🏵️": "roseta",
    "🌹": "rosa",
    "🥀": "flor murcha",
    "🌺": "hibisco",
    "🌻": "girassol",
    "🌼": "flor",
    "🌷": "tulipa",
    "🌱": "muda de planta",
    "🪴": "vaso com planta",
    "🌲": "conífera",
    "🌳": "árvore caidiça",
    "🌴": "palmeira",
    "🌵": "cacto",
    "🌾": "planta de arroz",
    "🌿": "erva",
    "☘️": "trevo",
    "🍀": "trevo de quatro folhas",
    "🍁": "folha de bordo",
    "🍂": "folhas caídas",
    "🍃": "folha ao vento",
    "🪹": "ninho vazio",
    "🪺": "ninho com ovos",
    "🍄": "cogumelo",
    "🌰": "castanha",
    "🦀": "caranguejo",
    "🦞": "lagosta",
    "🦐": "camarão",
    "🦑": "lula",
    "🌍": "globo mostrando europa e áfrica",
    "🌎": "globo mostrando as américas",
    "🌏": "globo mostrando ásia e oceania",
    "🌐": "globo com meridianos",
    "🪨": "pedra",
    "🌑": "lua nova",
    "🌒": "lua crescente côncava",
    "🌓": "quarto crescente",
    "🌔": "lua crescente convexa",
    "🌕": "lua cheia",
    "🌖": "lua minguante convexa",
    "🌗": "quarto minguante",
    "🌘": "lua minguante côncava",
    "🌙": "lua crescente",
    "🌚": "rosto da lua nova",
    "🌛": "rosto da lua de quarto crescente",
    "🌜": "rosto da lua de quarto minguante",
    "☀️": "sol",
    "🌝": "rosto da lua cheia",
    "🌞": "rosto do sol",
    "⭐": "estrela branca média",
    "🌟": "estrela brilhante",
    "🌠": "estrela cadente",
    "☁️": "nuvem",
    "⛅": "sol por trás das nuvens",
    "⛈️": "chuva com trovão",
    "🌤️": "sol com nuvens",
    "🌥️": "nublado",
    "🌦️": "sol com chuva",
    "🌧️": "nuvem com chuva",
    "🌨️": "nuvem com neve",
    "🌩️": "nuvem com trovão",
    "🌪️": "tornado",
    "🌫️": "nevoeiro",
    "🌬️": "rosto de vento",
    "🌈": "arco-íris",
    "☂️": "guarda-chuva",
    "☔": "sombrinha na chuva",
    "⚡": "alta tensão",
    "❄️": "floco de neve",
    "☃️": "boneco de neve",
    "⛄": "boneco de neve sem neve",
    "☄️": "cometa",
    "🔥": "fogo",
    "💧": "gota",
    "🌊": "onda",
    "🎄": "árvore de natal",
    "✨": "brilhos",
    "🎋": "árvore de tanabata",
    "🎍": "decoração de pinhos",
    "🫧": "bolhas",

    // https://emojipedia.org/pt/comida-bebida/
    "🍇": "uvas",
    "🍈": "melão",
    "🍉": "melancia",
    "🍊": "tangerina",
    "🍋": "limão",
    "🍌": "banana",
    "🍍": "abacaxi",
    "🥭": "manga",
    "🍎": "maçã vermelha",
    "🍏": "maçã verde",
    "🍐": "pera",
    "🍑": "pêssego",
    "🍒": "cereja",
    "🍓": "morango",
    "🫐": "mirtilos",
    "🥝": "kiwi",
    "🍅": "tomate",
    "🫒": "azeitona",
    "🥥": "coco",
    "🥑": "abacate",
    "🍆": "berinjela",
    "🥔": "batata",
    "🥕": "cenoura",
    "🌽": "milho",
    "🌶️": "pimenta",
    "🫑": "pimentão",
    "🥒": "pepino",
    "🥬": "verdura",
    "🥦": "brócolis",
    "🧄": "alho",
    "🧅": "cebola",
    "🍄": "cogumelo",
    "🥜": "amendoim",
    "🫘": "feijões",
    "🌰": "castanha",
    "🍞": "pão",
    "🥐": "croissant",
    "🥖": "baguete",
    "🫓": "pão sírio",
    "🥨": "pretzel",
    "🥯": "rosca",
    "🥞": "panquecas",
    "🧇": "waffle",
    "🧀": "queijo",
    "🍖": "carne",
    "🍗": "coxa de frango",
    "🥩": "corte de carne",
    "🥓": "bacon",
    "🍔": "hambúrguer",
    "🍟": "batata frita",
    "🍕": "pizza",
    "🌭": "cachorro-quente",
    "🥪": "sanduíche",
    "🌮": "taco",
    "🌯": "burrito",
    "🫔": "tamale",
    "🥙": "pão recheado",
    "🧆": "falafel",
    "🥚": "ovo",
    "🍳": "ovo frito",
    "🥘": "caçarola com comida",
    "🍲": "panela",
    "🫕": "fondue",
    "🥣": "tigela com colher",
    "🥗": "salada verde",
    "🍿": "pipoca",
    "🧈": "manteiga",
    "🧂": "sal",
    "🥫": "comida enlatada",
    "🍱": "bentô",
    "🍘": "biscoito de arroz",
    "🍙": "arroz japonês",
    "🍚": "arroz cozido",
    "🍛": "arroz com curry",
    "🍜": "lámen",
    "🍝": "espaguete",
    "🍠": "batata assada",
    "🍢": "oden",
    "🍣": "sushi",
    "🍤": "camarão frito",
    "🍥": "bolinho de peixe",
    "🥮": "bolo lunar",
    "🍡": "dango",
    "🥟": "bolinho asiático",
    "🥠": "biscoito da sorte",
    "🥡": "caixa para viagem",
    "🦪": "ostra",
    "🍦": "sorvete italiano",
    "🍧": "raspadinha de gelo",
    "🍨": "sorvete",
    "🍩": "donut",
    "🍪": "biscoito",
    "🎂": "bolo de aniversário",
    "🍰": "pão de ló de morango",
    "🧁": "cupcake",
    "🥧": "torta",
    "🍫": "chocolate",
    "🍬": "bala",
    "🍭": "pirulito",
    "🍮": "pudim",
    "🍯": "pote de mel",
    "🍼": "mamadeira",
    "🥛": "copo de leite",
    "☕": "café",
    "🫖": "bule",
    "🍵": "xícara de chá sem alça",
    "🍶": "saquê",
    "🍾": "garrafa de champanhe",
    "🍷": "vinho",
    "🍸": "coquetel",
    "🍹": "bebida tropical",
    "🍺": "cerveja",
    "🍻": "canecas de cerveja",
    "🥂": "taças brindando",
    "🥃": "copo",
    "🫗": "líquido a verter",
    "🥤": "copo com canudo",
    "🧋": "chá perolado",
    "🧃": "suco de caixa",
    "🧉": "mate",
    "🧊": "cubo de gelo",
    "🥢": "hashi",
    "🍽️": "prato com talheres",
    "🍴": "garfo e faca",
    "🥄": "colher",
    "🫙": "jarro",

    // https://emojipedia.org/pt/atividades/
    "🕴️": "pessoa de terno levitando",
    "🧗": "pessoa escalando",
    "🧗‍♂️": "homem escalando",
    "🧗‍♀️": "mulher escalando",
    "🤺": "esgrimista",
    "🏇": "corrida de cavalos",
    "⛷️": "esquiador",
    "🏂": "praticante de snowboard",
    "🏌️": "golfista",
    "🏌️‍♂️": "homem golfista",
    "🏌️‍♀️": "mulher golfista",
    "🏄": "surfista",
    "🏄‍♂️": "homem surfista",
    "🏄‍♀️": "mulher surfista",
    "🚣": "pessoa remando",
    "🚣‍♂️": "homem remando",
    "🚣‍♀️": "mulher remando",
    "🏊": "pessoa nadando",
    "🏊‍♂️": "homem nadando",
    "🏊‍♀️": "mulher nadando",
    "⛹️": "pessoa jogando basquete",
    "⛹️‍♂️": "homem jogando basquete",
    "⛹️‍♀️": "mulher jogando basquete",
    "🏋️": "pessoa levantando peso",
    "🏋️‍♂️": "homem levantando peso",
    "🏋️‍♀️": "mulher levantando peso",
    "🚴": "ciclista",
    "🚴‍♂️": "homem ciclista",
    "🚴‍♀️": "mulher ciclista",
    "🚵": "pessoa fazendo mountain bike",
    "🚵‍♂️": "homem fazendo mountain bike",
    "🚵‍♀️": "mulher fazendo mountain bike",
    "🤸": "pessoa fazendo estrela",
    "🤸‍♂️": "homem fazendo estrela",
    "🤸‍♀️": "mulher fazendo estrela",
    "🤼": "pessoas lutando",
    "🤼‍♂️": "homens lutando",
    "🤼‍♀️": "mulheres lutando",
    "🤽": "pessoa jogando polo aquático",
    "🤽‍♂️": "homem jogando polo aquático",
    "🤽‍♀️": "mulher jogando polo aquático",
    "🤾": "handebol",
    "🤾‍♂️": "jogador de handebol",
    "🤾‍♀️": "jogadora de handebol",
    "🤹": "malabarista",
    "🤹‍♂️": "homem malabarista",
    "🤹‍♀️": "mulher malabarista",
    "🧘": "pessoa na posição de lótus",
    "🧘‍♂️": "homem na posição de lótus",
    "🧘‍♀️": "mulher na posição de lótus",
    "🎪": "circo",
    "🛹": "skate",
    "🛼": "patins de rodas",
    "🛶": "canoa",
    "🎗️": "fita de lembrete",
    "🎟️": "ingresso de cinema",
    "🎫": "ingresso",
    "🎖️": "medalha militar",
    "🏆": "troféu",
    "🏅": "medalha esportiva",
    "🥇": "medalha de ouro",
    "🥈": "medalha de prata",
    "🥉": "medalha de bronze",
    "⚽": "bola de futebol",
    "⚾": "bola de beisebol",
    "🥎": "softbol",
    "🏀": "bola de basquete",
    "🏐": "bola de vôlei",
    "🏈": "bola de futebol americano",
    "🏉": "bola de rugby",
    "🎾": "tênis",
    "🥏": "frisbee",
    "🎳": "boliche",
    "🏏": "críquete",
    "🏑": "hóquei de campo",
    "🏒": "hóquei no gelo",
    "🥍": "lacrosse",
    "🏓": "pingue-pongue",
    "🏸": "badminton",
    "🥊": "luva de boxe",
    "🥋": "quimono de artes marciais",
    "🥅": "gol",
    "⛳": "bandeira no buraco",
    "⛸️": "patins de gelo",
    "🎣": "pesca",
    "🎽": "camiseta de corrida",
    "🎿": "esqui",
    "🛷": "trenó",
    "🥌": "pedra de curling",
    "🎯": "no alvo",
    "🎱": "bilhar",
    "🎮": "videogame",
    "🎰": "caça-níquel",
    "🎲": "jogo de dado",
    "🧩": "quebra-cabeça",
    "🪩": "bola espelhada",
    "♟️": "peão de xadrez",
    "🎭": "máscara",
    "🎨": "paleta de tintas",
    "🧵": "carretel",
    "🧶": "novelo",
    "🎼": "partitura musical",
    "🎤": "microfone",
    "🎧": "fones de ouvido",
    "🎷": "saxofone",
    "🪗": "acordeão",
    "🎸": "guitarra",
    "🎹": "teclado musical",
    "🎺": "trompete",
    "🎻": "violino",
    "🥁": "tambor",
    "🪘": "tambor comprido",
    "🎬": "claquete",
    "🏹": "arco e flecha",

    // https://emojipedia.org/pt/viaggi-luoghi/
    "🚣": "pessoa remando",
    "🗾": "mapa do japão",
    "🏔️": "montanha com neve",
    "⛰️": "montanha",
    "🌋": "vulcão",
    "🗻": "monte fuji",
    "🏕️": "acampamento",
    "🏖️": "praia e guarda-sol",
    "🏜️": "deserto",
    "🏝️": "ilha deserta",
    "🏞️": "parque nacional",
    "🏟️": "estádio",
    "🏛️": "prédio grego",
    "🏗️": "construção",
    "🛖": "cabana",
    "🏘️": "casas",
    "🏚️": "casa abandonada",
    "🏠": "casa",
    "🏡": "casa com jardim",
    "🏢": "edifício comercial",
    "🏣": "correio japonês",
    "🏤": "correio",
    "🏥": "hospital",
    "🏦": "banco",
    "🏨": "hotel",
    "🏩": "motel",
    "🏪": "loja de conveniência",
    "🏫": "escola",
    "🏬": "loja de departamentos",
    "🏭": "fábrica",
    "🏯": "castelo japonês",
    "🏰": "castelo",
    "💒": "capela de casamento",
    "🗼": "torre de tóquio",
    "🗽": "estátua da liberdade",
    "⛪": "igreja",
    "🕌": "mesquita",
    "🛕": "templo hindu",
    "🕍": "sinagoga",
    "⛩️": "santuário japonês",
    "🕋": "caaba islã",
    "⛲": "fonte",
    "⛺": "barraca",
    "🌁": "enevoado",
    "🌃": "noite estrelada",
    "🏙️": "cidade",
    "🌄": "aurora sobre montanhas",
    "🌅": "aurora sobre água",
    "🌆": "cidade ao anoitecer",
    "🌇": "pôr do sol",
    "🌉": "ponte à noite",
    "🎠": "carrossel",
    "🛝": "escorrega infantil",
    "🎡": "roda gigante",
    "🎢": "montanha russa",
    "🚂": "locomotiva",
    "🚃": "vagão de trem",
    "🚄": "trem de alta velocidade",
    "🚅": "trem de alta velocidade japonês",
    "🚆": "trem",
    "🚇": "metrô",
    "🚈": "trem urbano",
    "🚉": "estação",
    "🚊": "bonde elétrico",
    "🚝": "monotrilho",
    "🚞": "estrada de ferro na montanha",
    "🚋": "bonde",
    "🚌": "ônibus",
    "🚍": "ônibus se aproximando",
    "🚎": "trólebus",
    "🚐": "van",
    "🚑": "ambulância",
    "🚒": "carro do corpo de bombeiros",
    "🚓": "viatura policial",
    "🚔": "viatura policial se aproximando",
    "🚕": "táxi",
    "🚖": "táxi se aproximando",
    "🚗": "carro",
    "🚘": "carro se aproximando",
    "🚙": "suv",
    "🛻": "caminhonete",
    "🚚": "caminhão de entrega",
    "🚛": "caminhão",
    "🚜": "trator",
    "🏎️": "carro de corrida",
    "🏍️": "motocicleta",
    "🛵": "scooter",
    "🛺": "automóvel riquixá",
    "🚲": "bicicleta",
    "🛴": "patinete",
    "🚏": "ponto de ônibus",
    "🛣️": "estrada",
    "🛤️": "trilhos",
    "⛽": "posto de gasolina",
    "🛞": "roda",
    "🚨": "sirene",
    "🚥": "semáforo horizontal",
    "🚦": "semáforo vertical",
    "🚧": "em construção",
    "⚓": "âncora",
    "🛟": "bóia em anel",
    "⛵": "barco a vela",
    "🚤": "lancha",
    "🛳️": "cruzeiro",
    "⛴️": "balsa",
    "🛥️": "barco",
    "🚢": "navio",
    "✈️": "avião",
    "🛩️": "avião pequeno",
    "🛫": "avião decolando",
    "🛬": "avião aterrissando",
    "🪂": "paraquedas",
    "💺": "assento",
    "🚁": "helicóptero",
    "🚟": "estrada de ferro suspensa",
    "🚠": "cabo suspenso usado em teleféricos nas montanhas",
    "🚡": "teleférico",
    "🛰️": "satélite",
    "🚀": "foguete",
    "🛸": "disco voador",
    "🪐": "planeta com anéis",
    "🌠": "estrela cadente",
    "🌌": "via láctea",
    "⛱️": "guarda-sol",
    "🎆": "fogos de artifício",
    "🎇": "vela estrela",
    "🎑": "contemplação da lua",
    "💴": "nota de iene",
    "💵": "nota de dólar",
    "💶": "nota de euro",
    "💷": "nota de libra",
    "🗿": "moai",
    "🛂": "controle de passaportes",
    "🛃": "alfândega",
    "🛄": "restituição de bagagem",
    "🛅": "depósito de bagagem",

    // https://emojipedia.org/pt/objetos/
    "💌": "carta de amor",
    "🕳️": "buraco",
    "💣": "bomba",
    "🛀": "pessoa tomando banho",
    "🛌": "pessoa deitada na cama",
    "🔪": "faca de cozinha",
    "🏺": "ânfora",
    "🗺️": "mapa-múndi",
    "🧭": "bússola",
    "🧱": "tijolo",
    "💈": "barbearia",
    "🦽": "cadeira de rodas manual",
    "🦼": "cadeira de rodas motorizada",
    "🛢️": "barril de óleo",
    "🛎️": "sineta",
    "🧳": "mala",
    "⌛": "ampulheta",
    "⏳": "ampulheta contando o tempo",
    "⌚": "relógio de pulso",
    "⏰": "despertador",
    "⏱️": "cronômetro",
    "⏲️": "relógio temporizador",
    "🕰️": "relógio de mesa",
    "🌡️": "termômetro",
    "⛱️": "guarda-sol",
    "🧨": "bombinha",
    "🎈": "balão",
    "🎉": "cone de festa",
    "🎊": "confete",
    "🎎": "bonecas japonesas",
    "🎏": "bandeira de carpas",
    "🎐": "carrilhão de vento",
    "🧧": "envelope vermelho",
    "🎀": "laço de fita",
    "🎁": "presente",
    "🤿": "máscara de mergulho",
    "🪀": "ioiô",
    "🪁": "pipa",
    "🔮": "bola de cristal",
    "🪄": "varinha mágica",
    "🧿": "olho grego",
    "🪬": "mão hamsá",
    "🕹️": "joystick",
    "🧸": "ursinho de pelúcia",
    "🪅": "pinhata",
    "🪆": "boneca russa",
    "🖼️": "quadro emoldurado",
    "🧵": "carretel",
    "🪡": "agulha de costura",
    "🧶": "novelo",
    "🪢": "nó",
    "🛍️": "sacolas de compras",
    "📿": "rosário de oração",
    "💎": "pedra preciosa",
    "📯": "corneta postal",
    "🎙️": "microfone de estúdio",
    "🎚️": "controle de volume",
    "🎛️": "botões giratórios",
    "📻": "rádio",
    "🪕": "banjo",
    "📱": "telefone celular",
    "📲": "telefone celular com seta",
    "☎️": "telefone no gancho",
    "📞": "telefone",
    "📟": "pager",
    "📠": "fax",
    "🔋": "pilha",
    "🔌": "tomada elétrica",
    "💻": "laptop",
    "🖥️": "computador de mesa",
    "🖨️": "impressora",
    "⌨️": "teclado",
    "🖱️": "mouse",
    "🖲️": "trackball",
    "💽": "minidisc",
    "💾": "disquete",
    "💿": "cd",
    "📀": "dvd",
    "🧮": "ábaco",
    "🎥": "câmera de cinema",
    "🎞️": "rolo de filmes",
    "📽️": "projetor de filmes",
    "📺": "televisão",
    "📷": "câmera",
    "📸": "câmera com flash",
    "📹": "câmera de vídeo",
    "📼": "videocassete",
    "🔍": "lupa para a esquerda",
    "🔎": "lupa para a direita",
    "🕯️": "vela",
    "💡": "lâmpada",
    "🔦": "lanterna",
    "🏮": "lanterna vermelha de papel",
    "🪔": "lâmpada de óleo",
    "📔": "caderno decorado",
    "📕": "livro fechado",
    "📖": "livro aberto",
    "📗": "livro verde",
    "📘": "livro azul",
    "📙": "livro laranja",
    "📚": "livros",
    "📓": "caderno",
    "📒": "livro contábil",
    "📃": "página dobrada",
    "📜": "pergaminho",
    "📄": "página voltada para cima",
    "📰": "jornal",
    "🗞️": "jornal enrolado",
    "📑": "marcadores de página",
    "🔖": "marcador de página",
    "🏷️": "etiqueta",
    "💰": "saco de dinheiro",
    "🪙": "moeda",
    "💴": "nota de iene",
    "💵": "nota de dólar",
    "💶": "nota de euro",
    "💷": "nota de libra",
    "💸": "dinheiro voando",
    "💳": "cartão de crédito",
    "🧾": "recibo",
    "✉️": "envelope",
    "📧": "e-mail",
    "📨": "envelope chegando",
    "📩": "envelope com seta",
    "📤": "bandeja de saída",
    "📥": "bandeja de entrada",
    "📦": "pacote",
    "📫": "caixa de correio fechada com bandeira levantada",
    "📪": "caixa de correio fechada com bandeira abaixada",
    "📬": "caixa de correio aberta com bandeira levantada",
    "📭": "caixa de correio aberta com bandeira abaixada",
    "📮": "caixa de correio",
    "🗳️": "urna eleitoral com cédula",
    "✏️": "lápis",
    "✒️": "ponta de caneta tinteiro",
    "🖋️": "caneta tinteiro",
    "🖊️": "caneta",
    "🖌️": "pincel",
    "🖍️": "giz de cera",
    "📝": "memorando",
    "📁": "pasta de arquivos",
    "📂": "pasta de arquivos aberta",
    "🗂️": "divisores de pastas",
    "📅": "calendário",
    "📆": "calendário com folhas destacáveis",
    "🗒️": "bloco espiral",
    "🗓️": "calendário espiral",
    "📇": "índice de cartões",
    "📈": "gráfico subindo",
    "📉": "gráfico caindo",
    "📊": "gráfico de barras",
    "📋": "prancheta",
    "📌": "tacha",
    "📍": "tacha redonda",
    "📎": "clipe de papel",
    "🖇️": "clipes de papel conectados",
    "📏": "régua reta",
    "📐": "régua triangular",
    "✂️": "tesoura",
    "🗃️": "caixa de arquivos",
    "🗄️": "gavetas de escritório",
    "🗑️": "lixeira",
    "🔒": "cadeado",
    "🔓": "cadeado aberto",
    "🔏": "cadeado com caneta",
    "🔐": "cadeado fechado com chave",
    "🔑": "chave",
    "🗝️": "chave antiga",
    "🔨": "martelo",
    "🪓": "machado",
    "⛏️": "picareta",
    "⚒️": "martelo e picareta",
    "🛠️": "martelo e chave-inglesa",
    "🗡️": "adaga",
    "⚔️": "espadas cruzadas",
    "🔫": "pistola d’água",
    "🪃": "bumerangue",
    "🛡️": "escudo",
    "🪚": "serrote",
    "🔧": "chave inglesa",
    "🪛": "chave de fenda",
    "🔩": "porca e parafuso",
    "⚙️": "engrenagem",
    "🗜️": "braçadeira",
    "⚖️": "balança",
    "🦯": "bengala para cegos",
    "🔗": "link",
    "⛓️": "correntes",
    "🪝": "gancho",
    "🧰": "caixa de ferramentas",
    "🧲": "ímã",
    "🪜": "escada",
    "⚗️": "alambique",
    "🧪": "tubo de ensaio",
    "🧫": "placa de petri",
    "🧬": "dna",
    "🔬": "microscópio",
    "🔭": "telescópio",
    "📡": "antena parabólica",
    "💉": "seringa",
    "🩸": "gota de sangue",
    "💊": "comprimido",
    "🩹": "atadura adesiva",
    "🩼": "muleta",
    "🩺": "estetoscópio",
    "🚪": "porta",
    "🪞": "espelho",
    "🪟": "janela",
    "🛏️": "cama",
    "🛋️": "sofá e luminária",
    "🪑": "cadeira",
    "🚽": "vaso sanitário",
    "🪠": "desentupidor",
    "🚿": "chuveiro",
    "🛁": "banheira",
    "🪤": "ratoeira",
    "🪒": "lâmina",
    "🧴": "frasco de loção",
    "🧷": "alfinete de segurança",
    "🧹": "vassoura",
    "🧺": "cesta",
    "🧻": "rolo de papel",
    "🪣": "balde",
    "🧼": "sabonete",
    "🪥": "escova de dentes",
    "🧽": "esponja",
    "🧯": "extintor de incêndio",
    "🛒": "carrinho de compras",
    "🚬": "cigarro",
    "⚰️": "caixão",
    "🪦": "lápide",
    "⚱️": "urna funerária",
    "🗿": "moai",
    "🪧": "placa",
    "🪪": "cartão de identificação",
    "🚰": "água potável",

    // https://emojipedia.org/pt/bandeiras/
    "🏁": "bandeira quadriculada",
    "🚩": "bandeira triangular",
    "🎌": "bandeiras cruzadas",
    "🏴": "bandeira preta",
    "🏳️": "bandeira branca",
    "🏳️‍🌈": "bandeira do arco-íris",
    "🏳️‍⚧️": "bandeira transgênero",
    "🏴‍☠️": "bandeira de pirata",
    "🇦🇨": "bandeira: ilha de ascensão",
    "🇦🇩": "bandeira: andorra",
    "🇦🇪": "bandeira: emirados árabes unidos",
    "🇦🇫": "bandeira: afeganistão",
    "🇦🇬": "bandeira: antígua e barbuda",
    "🇦🇮": "bandeira: anguila",
    "🇦🇱": "bandeira: albânia",
    "🇦🇲": "bandeira: armênia",
    "🇦🇴": "bandeira: angola",
    "🇦🇶": "bandeira: antártida",
    "🇦🇷": "bandeira: argentina",
    "🇦🇸": "bandeira: samoa americana",
    "🇦🇹": "bandeira: áustria",
    "🇦🇺": "bandeira: austrália",
    "🇦🇼": "bandeira: aruba",
    "🇦🇽": "bandeira: ilhas aland",
    "🇦🇿": "bandeira: azerbaijão",
    "🇧🇦": "bandeira: bósnia e herzegovina",
    "🇧🇧": "bandeira: barbados",
    "🇧🇩": "bandeira: bangladesh",
    "🇧🇪": "bandeira: bélgica",
    "🇧🇫": "bandeira: burquina faso",
    "🇧🇬": "bandeira: bulgária",
    "🇧🇭": "bandeira: barein",
    "🇧🇮": "bandeira: burundi",
    "🇧🇯": "bandeira: benin",
    "🇧🇱": "bandeira: são bartolomeu",
    "🇧🇲": "bandeira: bermudas",
    "🇧🇳": "bandeira: brunei",
    "🇧🇴": "bandeira: bolívia",
    "🇧🇶": "bandeira: países baixos caribenhos",
    "🇧🇷": "bandeira: brasil",
    "🇧🇸": "bandeira: bahamas",
    "🇧🇹": "bandeira: butão",
    "🇧🇻": "bandeira: ilha bouvet",
    "🇧🇼": "bandeira: botsuana",
    "🇧🇾": "bandeira: bielorrússia",
    "🇧🇿": "bandeira: belize",
    "🇨🇦": "bandeira: canadá",
    "🇨🇨": "bandeira: ilhas cocos (keeling)",
    "🇨🇩": "bandeira: congo - kinshasa",
    "🇨🇫": "bandeira: república centro-africana",
    "🇨🇬": "bandeira: república do congo",
    "🇨🇭": "bandeira: suíça",
    "🇨🇮": "bandeira: costa do marfim",
    "🇨🇰": "bandeira: ilhas cook",
    "🇨🇱": "bandeira: chile",
    "🇨🇲": "bandeira: camarões",
    "🇨🇳": "bandeira: china",
    "🇨🇴": "bandeira: colômbia",
    "🇨🇵": "bandeira: ilha de clipperton",
    "🇨🇷": "bandeira: costa rica",
    "🇨🇺": "bandeira: cuba",
    "🇨🇻": "bandeira: cabo verde",
    "🇨🇼": "bandeira: curaçao",
    "🇨🇽": "bandeira: ilha christmas",
    "🇨🇾": "bandeira: chipre",
    "🇨🇿": "bandeira: tchéquia",
    "🇩🇪": "bandeira: alemanha",
    "🇩🇬": "bandeira: diego garcia",
    "🇩🇯": "bandeira: djibuti",
    "🇩🇰": "bandeira: dinamarca",
    "🇩🇲": "bandeira: dominica",
    "🇩🇴": "bandeira: república dominicana",
    "🇩🇿": "bandeira: argélia",
    "🇪🇦": "bandeira: ceuta e melilla",
    "🇪🇨": "bandeira: equador",
    "🇪🇪": "bandeira: estônia",
    "🇪🇬": "bandeira: egito",
    "🇪🇭": "bandeira: saara ocidental",
    "🇪🇷": "bandeira: eritreia",
    "🇪🇸": "bandeira: espanha",
    "🇪🇹": "bandeira: etiópia",
    "🇪🇺": "flag: european union",
    "🇫🇮": "bandeira: finlândia",
    "🇫🇯": "bandeira: fiji",
    "🇫🇰": "bandeira: ilhas malvinas",
    "🇫🇲": "bandeira: micronésia",
    "🇫🇴": "bandeira: ilhas faroé",
    "🇫🇷": "bandeira: frança",
    "🇬🇦": "bandeira: gabão",
    "🇬🇧": "bandeira: reino unido",
    "🇬🇩": "bandeira: granada",
    "🇬🇪": "bandeira: geórgia",
    "🇬🇫": "bandeira: guiana francesa",
    "🇬🇬": "bandeira: guernsey",
    "🇬🇭": "bandeira: gana",
    "🇬🇮": "bandeira: gibraltar",
    "🇬🇱": "bandeira: groenlândia",
    "🇬🇲": "bandeira: gâmbia",
    "🇬🇳": "bandeira: guiné",
    "🇬🇵": "bandeira: guadalupe",
    "🇬🇶": "bandeira: guiné equatorial",
    "🇬🇷": "bandeira: grécia",
    "🇬🇸": "bandeira: ilhas geórgia do sul e sandwich do sul",
    "🇬🇹": "bandeira: guatemala",
    "🇬🇺": "bandeira: guam",
    "🇬🇼": "bandeira: guiné-bissau",
    "🇬🇾": "bandeira: guiana",
    "🇭🇰": "bandeira: hong kong, rae da china",
    "🇭🇲": "bandeira: ilhas heard e mcdonald",
    "🇭🇳": "bandeira: honduras",
    "🇭🇷": "bandeira: croácia",
    "🇭🇹": "bandeira: haiti",
    "🇭🇺": "bandeira: hungria",
    "🇮🇨": "bandeira: ilhas canárias",
    "🇮🇩": "bandeira: indonésia",
    "🇮🇪": "bandeira: irlanda",
    "🇮🇱": "bandeira: israel",
    "🇮🇲": "bandeira: ilha de man",
    "🇮🇳": "bandeira: índia",
    "🇮🇴": "bandeira: território britânico do oceano índico",
    "🇮🇶": "bandeira: iraque",
    "🇮🇷": "bandeira: irã",
    "🇮🇸": "bandeira: islândia",
    "🇮🇹": "bandeira: itália",
    "🇯🇪": "bandeira: jersey",
    "🇯🇲": "bandeira: jamaica",
    "🇯🇴": "bandeira: jordânia",
    "🇯🇵": "bandeira: japão",
    "🇰🇪": "bandeira: quênia",
    "🇰🇬": "bandeira: quirguistão",
    "🇰🇭": "bandeira: camboja",
    "🇰🇮": "bandeira: quiribati",
    "🇰🇲": "bandeira: comores",
    "🇰🇳": "bandeira: são cristóvão e névis",
    "🇰🇵": "bandeira: coreia do norte",
    "🇰🇷": "bandeira: coreia do sul",
    "🇰🇼": "bandeira: kuwait",
    "🇰🇾": "bandeira: ilhas cayman",
    "🇰🇿": "bandeira: cazaquistão",
    "🇱🇦": "bandeira: laos",
    "🇱🇧": "bandeira: líbano",
    "🇱🇨": "bandeira: santa lúcia",
    "🇱🇮": "bandeira: liechtenstein",
    "🇱🇰": "bandeira: sri lanka",
    "🇱🇷": "bandeira: libéria",
    "🇱🇸": "bandeira: lesoto",
    "🇱🇹": "bandeira: lituânia",
    "🇱🇺": "bandeira: luxemburgo",
    "🇱🇻": "bandeira: letônia",
    "🇱🇾": "bandeira: líbia",
    "🇲🇦": "bandeira: marrocos",
    "🇲🇨": "bandeira: mônaco",
    "🇲🇩": "bandeira: moldávia",
    "🇲🇪": "bandeira: montenegro",
    "🇲🇫": "bandeira: são martinho",
    "🇲🇬": "bandeira: madagascar",
    "🇲🇭": "bandeira: ilhas marshall",
    "🇲🇰": "bandeira: macedônia do norte",
    "🇲🇱": "bandeira: mali",
    "🇲🇲": "bandeira: mianmar (birmânia)",
    "🇲🇳": "bandeira: mongólia",
    "🇲🇴": "bandeira: macau, rae da china",
    "🇲🇵": "bandeira: ilhas marianas do norte",
    "🇲🇶": "bandeira: martinica",
    "🇲🇷": "bandeira: mauritânia",
    "🇲🇸": "bandeira: montserrat",
    "🇲🇹": "bandeira: malta",
    "🇲🇺": "bandeira: maurício",
    "🇲🇻": "bandeira: maldivas",
    "🇲🇼": "bandeira: malaui",
    "🇲🇽": "bandeira: méxico",
    "🇲🇾": "bandeira: malásia",
    "🇲🇿": "bandeira: moçambique",
    "🇳🇦": "bandeira: namíbia",
    "🇳🇨": "bandeira: nova caledônia",
    "🇳🇪": "bandeira: níger",
    "🇳🇫": "bandeira: ilha norfolk",
    "🇳🇬": "bandeira: nigéria",
    "🇳🇮": "bandeira: nicarágua",
    "🇳🇱": "bandeira: países baixos",
    "🇳🇴": "bandeira: noruega",
    "🇳🇵": "bandeira: nepal",
    "🇳🇷": "bandeira: nauru",
    "🇳🇺": "bandeira: niue",
    "🇳🇿": "bandeira: nova zelândia",
    "🇴🇲": "bandeira: omã",
    "🇵🇦": "bandeira: panamá",
    "🇵🇪": "bandeira: peru",
    "🇵🇫": "bandeira: polinésia francesa",
    "🇵🇬": "bandeira: papua-nova guiné",
    "🇵🇭": "bandeira: filipinas",
    "🇵🇰": "bandeira: paquistão",
    "🇵🇱": "bandeira: polônia",
    "🇵🇲": "bandeira: são pedro e miquelão",
    "🇵🇳": "bandeira: ilhas pitcairn",
    "🇵🇷": "bandeira: porto rico",
    "🇵🇸": "bandeira: territórios palestinos",
    "🇵🇹": "bandeira: portugal",
    "🇵🇼": "bandeira: palau",
    "🇵🇾": "bandeira: paraguai",
    "🇶🇦": "bandeira: catar",
    "🇷🇪": "bandeira: reunião",
    "🇷🇴": "bandeira: romênia",
    "🇷🇸": "bandeira: sérvia",
    "🇷🇺": "bandeira: rússia",
    "🇷🇼": "bandeira: ruanda",
    "🇸🇦": "bandeira: arábia saudita",
    "🇸🇧": "bandeira: ilhas salomão",
    "🇸🇨": "bandeira: seicheles",
    "🇸🇩": "bandeira: sudão",
    "🇸🇪": "bandeira: suécia",
    "🇸🇬": "bandeira: singapura",
    "🇸🇭": "bandeira: santa helena",
    "🇸🇮": "bandeira: eslovênia",
    "🇸🇯": "bandeira: svalbard e jan mayen",
    "🇸🇰": "bandeira: eslováquia",
    "🇸🇱": "bandeira: serra leoa",
    "🇸🇲": "bandeira: san marino",
    "🇸🇳": "bandeira: senegal",
    "🇸🇴": "bandeira: somália",
    "🇸🇷": "bandeira: suriname",
    "🇸🇸": "bandeira: sudão do sul",
    "🇸🇹": "bandeira: são tomé e príncipe",
    "🇸🇻": "bandeira: el salvador",
    "🇸🇽": "bandeira: sint maarten",
    "🇸🇾": "bandeira: síria",
    "🇸🇿": "bandeira: essuatíni",
    "🇹🇦": "bandeira: tristão da cunha",
    "🇹🇨": "bandeira: ilhas turcas e caicos",
    "🇹🇩": "bandeira: chade",
    "🇹🇫": "bandeira: territórios franceses do sul",
    "🇹🇬": "bandeira: togo",
    "🇹🇭": "bandeira: tailândia",
    "🇹🇯": "bandeira: tadjiquistão",
    "🇹🇰": "bandeira: tokelau",
    "🇹🇱": "bandeira: timor-leste",
    "🇹🇲": "bandeira: turcomenistão",
    "🇹🇳": "bandeira: tunísia",
    "🇹🇴": "bandeira: tonga",
    "🇹🇷": "bandeira: turquia",
    "🇹🇹": "bandeira: trinidad e tobago",
    "🇹🇻": "bandeira: tuvalu",
    "🇹🇼": "bandeira: taiwan",
    "🇹🇿": "bandeira: tanzânia",
    "🇺🇦": "bandeira: ucrânia",
    "🇺🇬": "bandeira: uganda",
    "🇺🇲": "bandeira: ilhas menores distantes dos eua",
    "🇺🇳": "bandeira: nações unidas",
    "🇺🇸": "bandeira: estados unidos",
    "🇺🇾": "bandeira: uruguai",
    "🇺🇿": "bandeira: uzbequistão",
    "🇻🇦": "bandeira: cidade do vaticano",
    "🇻🇨": "bandeira: são vicente e granadinas",
    "🇻🇪": "bandeira: venezuela",
    "🇻🇬": "bandeira: ilhas virgens britânicas",
    "🇻🇮": "bandeira: ilhas virgens americanas",
    "🇻🇳": "bandeira: vietnã",
    "🇻🇺": "bandeira: vanuatu",
    "🇼🇫": "bandeira: wallis e futuna",
    "🇼🇸": "bandeira: samoa",
    "🇽🇰": "bandeira: kosovo",
    "🇾🇪": "bandeira: iêmen",
    "🇾🇹": "bandeira: mayotte",
    "🇿🇦": "bandeira: áfrica do sul",
    "🇿🇲": "bandeira: zâmbia",
    "🇿🇼": "bandeira: zimbábue",
    "🏴󠁧󠁢󠁥󠁮󠁧󠁿": "bandeira: inglaterra",
    "🏴󠁧󠁢󠁳󠁣󠁴󠁿": "bandeira: escócia",
    "🏴󠁧󠁢󠁷󠁬󠁳󠁿": "bandeira: país de gales",
    "🏴󠁵󠁳󠁴󠁸󠁿": "bandeira de texas (us-tx)",

    // https://emojipedia.org/symbols/
    "💘": "coração com flecha",
    "💝": "coração com fita",
    "💖": "coração brilhante",
    "💗": "coração crescendo",
    "💓": "coração batendo",
    "💞": "corações girando",
    "💕": "dois corações",
    "💟": "coração decorativo",
    "❣️": "exclamação de coração",
    "💔": "coração partido",
    "❤️‍🔥": "coração pegando fogo",
    "❤️‍🩹": "coração com faixa",
    "❤️": "coração vermelho",
    "🧡": "coração laranja",
    "💛": "coração amarelo",
    "💚": "coração verde",
    "💙": "coração azul",
    "💜": "coração roxo",
    "🤎": "coração marrom",
    "🖤": "coração preto",
    "🤍": "coração branco",
    "💯": "cem pontos",
    "💢": "símbolo de raiva",
    "💬": "balão de diálogo",
    "👁️‍🗨️": "olho no balão de diálogo",
    "🗨️": "balão de diálogo à esquerda",
    "🗯️": "balão de raiva à direita",
    "💭": "balão de pensamento",
    "💤": "zzz",
    "💮": "flor branca",
    "♨️": "chamas",
    "💈": "barbearia",
    "🛑": "sinal de pare",
    "🕛": "12 horas",
    "🕧": "Doze E Meia",
    "🕐": "1 Hora",
    "🕜": "Uma E Meia",
    "🕑": "2 Horas",
    "🕝": "Duas E Meia",
    "🕒": "3 Horas",
    "🕞": "Três E Meia",
    "🕓": "4 Horas",
    "🕟": "Quatro E Meia",
    "🕔": "5 Horas",
    "🕠": "Cinco E Meia",
    "🕕": "6 Horas",
    "🕡": "Seis E Meia",
    "🕖": "7 Horas",
    "🕢": "Sete E Meia",
    "🕗": "8 Horas",
    "🕣": "Oito E Meia",
    "🕘": "9 Horas",
    "🕤": "Nove E Meia",
    "🕙": "10 Horas",
    "🕥": "Dez e Meia",
    "🕚": "11 Horas",
    "🕦": "Onze E Meia",
    "🌀": "ciclone",
    "♠️": "Naipe De Espadas",
    "♥️": "Naipe De Copas",
    "♦️": "Naipe De Ouros",
    "♣️": "Naipe De Paus",
    "🃏": "Curinga",
    "🀄": "Dragão Vermelho De Mahjong",
    "🎴": "Carta De Flores",
    "🔇": "Alto-Falante Silenciado",
    "🔈": "Alto-Falante Com Volume Baixo",
    "🔉": "Alto-Falante Com Volume Médio",
    "🔊": "Alto-Falante Com Volume Alto",
    "📢": "buzina",
    "📣": "megafone",
    "📯": "Corneta Postal",
    "🔔": "sino",
    "🔕": "sino silenciado",
    "🎵": "nota musical",
    "🎶": "notas musicais",
    "💹": "Gráfico Subindo Com Iene",
    "🛗": "Elevador",
    "🏧": "Símbolo De Caixa Automático",
    "🚮": "Símbolo De Lixeira",
    "🚰": "Água Potável",
    "♿": "Símbolo De Cadeira De Rodas",
    "🚹": "Banheiro Masculino",
    "🚺": "Banheiro Feminino",
    "🚻": "Banheiro",
    "🚼": "Símbolo De Bebê",
    "🚾": "wc",
    "⚠️": "Aviso",
    "🚸": "Crianças Atravessando",
    "⛔": "Entrada Proibida",
    "🚫": "proibido",
    "🚳": "Proibido Andar De Bicicleta",
    "🚭": "Proibido Fumar",
    "🚯": "Proibido Jogar Lixo No Chão",
    "🚱": "Água Não Potável",
    "🚷": "Proibida A Passagem De Pedestres",
    "📵": "Proibido O Uso De Telefone Celular",
    "🔞": "Proibido Para Menores De 18 Anos",
    "☢️": "radioativo",
    "☣️": "risco biológico",
    "⬆️": "Seta Para Cima",
    "↗️": "Seta Para Cima E Para A Direita",
    "➡️": "seta para a direita",
    "↘️": "seta para baixo e para a direita",
    "⬇️": "seta para baixo",
    "↙️": "seta para baixo e para a esquerda",
    "⬅️": "seta para a esquerda",
    "↖️": "seta para cima e para a esquerda",
    "↕️": "Seta Para Cima E Para Baixo",
    "↔️": "Seta Para Esquerda E Direita",
    "↩️": "Seta Curva Da Direita Para A Esquerda",
    "↪️": "Seta Curva Da Esquerda Para A Direita",
    "⤴️": "Seta Para A Direita Curvada Para Cima",
    "⤵️": "Seta Para A Direita Curvada Para Baixo",
    "🔃": "Setas Verticais No Sentido Horário",
    "🔄": "Botão De Setas Em Sentido Anti-Horário",
    "🔙": "Seta \"Back\"",
    "🔚": "Seta \"End\"",
    "🔛": "Seta \"On!\"",
    "🔜": "Seta \"Soon\"",
    "🔝": "Seta \"Top\"",
    "🛐": "local de culto",
    "⚛️": "símbolo de átomo",
    "🕉️": "om",
    "✡️": "estrela de davi",
    "☸️": "roda do dharma",
    "☯️": "yin yang",
    "✝️": "cruz latina",
    "☦️": "cruz ortodoxa",
    "☪️": "estrela e lua crescente",
    "☮️": "símbolo da paz",
    "🕎": "menorá",
    "🔯": "estrela de seis pontas",
    "♈": "signo de áries",
    "♉": "signo de touro",
    "♊": "signo de gêmeos",
    "♋": "signo de câncer",
    "♌": "signo de leão",
    "♍": "signo de virgem",
    "♎": "signo de libra",
    "♏": "signo de escorpião",
    "♐": "signo de sagitário",
    "♑": "signo de capricórnio",
    "♒": "signo de aquário",
    "♓": "signo de peixes",
    "⛎": "signo de ofiúco",
    "🔀": "Botão De Músicas Aleatórias",
    "🔁": "Botão De Repetir",
    "🔂": "Botão De Repetir Uma Única Faixa",
    "▶️": "Botão Reproduzir",
    "⏩": "Botão Avançar",
    "⏭️": "Botão De Próxima Faixa",
    "⏯️": "Botão De Reproduzir Ou Pausar",
    "◀️": "Botão De Voltar",
    "⏪": "Botão De Retroceder",
    "⏮️": "Botão De Faixa Anterior",
    "🔼": "Botão Apontando Para Cima",
    "⏫": "Botão De Avanço Para Cima",
    "🔽": "Botão Apontando Para Baixo",
    "⏬": "Botão De Avanço Para Baixo",
    "⏸️": "Botão Pausar",
    "⏹️": "Botão Parar",
    "⏺️": "Botão Gravar",
    "⏏️": "Botão Ejetar",
    "🎦": "cinema",
    "🔅": "Botão De Diminuir Brilho",
    "🔆": "Botão De Aumentar Brilho",
    "📶": "Barras De Sinal",
    "📳": "Modo Vibratório",
    "📴": "Telefone Celular Desligado",
    "♀️": "Símbolo De Feminino",
    "♂️": "Símbolo De Masculino",
    "✖️": "Sinal De Multiplicação",
    "➕": "Sinal De Adição",
    "➖": "Sinal De Subtração",
    "➗": "Sinal De Divisão",
    "🟰": "Sinal De Igual A em Negrito",
    "♾️": "infinito",
    "‼️": "Dupla Exclamação",
    "⁉️": "Exclamação Com Interrogação",
    "❓": "Ponto De Interrogação Vermelho",
    "❔": "Ponto De Interrogação Branco",
    "❕": "Ponto De Exclamação Branco",
    "❗": "Ponto De Exclamação Vermelho",
    "〰️": "Travessão Ondulado",
    "💱": "Câmbio De Moeda",
    "💲": "Cifrão",
    "⚕️": "Símbolo Da Medicina",
    "♻️": "Símbolo De Reciclagem",
    "⚜️": "Símbolo De Reciclagem",
    "🔱": "Emblema De Tridente",
    "📛": "Crachá",
    "🔰": "Símbolo Japonês De Principiante",
    "⭕": "Círculo Grande Oco",
    "✅": "Marca De Seleção Branca",
    "☑️": "Caixa De Seleção Marcada Com Tique",
    "✔️": "Marca De Seleção",
    "❌": "Xis",
    "❎": "Botão De Xis",
    "➰": "Laço Encaracolado",
    "➿": "Loop Encaracolado Duas Vezes",
    "〽️": "Sinal Japonês Indicando Início De Música",
    "✳️": "Asterisco De Oito Pontas",
    "✴️": "Estrela De Oito Pontas",
    "❇️": "Faísca",
    "©️": "símbolo de copyright",
    "®️": "Símbolo De Registrado",
    "™️": "Símbolo De Marca Registrada",
    "#️⃣": "tecla: cerquilha",
    "*️⃣": "tecla: asterisco",
    "0️⃣": "tecla: dígito zero",
    "1️⃣": "tecla: dígito um",
    "2️⃣": "tecla: dígito dois",
    "3️⃣": "tecla: dígito três",
    "4️⃣": "tecla: dígito quatro",
    "5️⃣": "tecla: dígito cinco",
    "6️⃣": "tecla: dígito seis",
    "7️⃣": "tecla: dígito sete",
    "8️⃣": "tecla: dígito oito",
    "9️⃣": "tecla: dígito nove",
    "🔟": "tecla: 10",
    "🔠": "Letras Latinas Maiúsculas",
    "🔡": "Letras Latinas Minúsculas",
    "🔢": "Números",
    "🔣": "Símbolos",
    "🔤": "Letras Latinas",
    "🅰️": "A (Tipo Sanguíneo)",
    "🆎": "ab (Tipo Sanguíneo)",
    "🅱️": "b (Tipo Sanguíneo)",
    "🆑": "Botão CL (CLear)",
    "🆒": "Botão \"Cool\"",
    "🆓": "Botão \"Free\"",
    "ℹ️": "Informações",
    "🆔": "Botão ID",
    "ⓜ️": "Círculo Com A Letra M",
    "🆕": "Botão \"New\"",
    "🆖": "Botão Ng (No Good)",
    "🅾️": "o (tipo sanguíneo)",
    "🆗": "Botão ok",
    "🅿️": "botão p",
    "🆘": "botão sos",
    "🆙": "Botão \"Up!\"",
    "🆚": "Botão Vs (Versus)",
    "🈁": "Botão Japonês De \"Aqui\"",
    "🈂️": "Botão Japonês De \"Taxa De Serviço\"",
    "🈷️": "Botão Japonês De \"Quantidade Mensal\"",
    "🈶": "Botão Japonês De \"Não Gratuito\"",
    "🈯": "Botão Japonês De \"Reservado\"",
    "🉐": "Botão Japonês De \"Barganha\"",
    "🈹": "Botão Japonês De \"Desconto\"",
    "🈚": "Botão Japonês De \"Gratuito\"",
    "🈲": "Botão Japonês De \"Proibido\"",
    "🉑": "Botão Japonês De \"Aceitável\"",
    "🈸": "Botão Japonês De \"Aplicação\"",
    "🈴": "Botão Japonês De \"Nota Mínima\"",
    "🈳": "Botão Japonês De \"Vago\"",
    "㊗️": "Botão Japonês De \"Parabéns\"",
    "㊙️": "Botão Japonês De \"Segredo\"",
    "🈺": "Botão Japonês De \"Aberto Para Negócios\"",
    "🈵": "Botão Japonês De \"Sem Vagas\"",
    "🔴": "círculo vermelho",
    "🟠": "círculo laranja",
    "🟡": "círculo amarelo",
    "🟢": "círculo verde",
    "🔵": "círculo azul",
    "🟣": "círculo roxo",
    "🟤": "círculo marrom",
    "⚫": "círculo preto",
    "⚪": "círculo branco",
    "🟥": "quadrado vermelho",
    "🟧": "quadrado laranja",
    "🟨": "quadrado amarelo",
    "🟩": "quadrado verde",
    "🟦": "quadrado azul",
    "🟪": "quadrado roxo",
    "🟫": "quadrado marrom",
    "⬛": "Quadrado Preto Grande",
    "⬜": "Quadrado branco Grande",
    "◼️": "Quadrado Preto médio",
    "◻️": "Quadrado branco médio",
    "◾": "Quadrado Preto Médio Menor",
    "◽": "Quadrado Branco Médio Menor",
    "▪️": "Quadrado Preto pequeno",
    "▫️": "Quadrado Branco pequeno",
    "🔶": "Losango Laranja Grande",
    "🔷": "Losango azul Grande",
    "🔸": "Losango Laranja Pequeno",
    "🔹": "Losango azul Pequeno",
    "🔺": "Triângulo Vermelho Para Cima",
    "🔻": "Triângulo Vermelho Para Baixo",
    "💠": "Diamante Com Um Ponto",
    "🔘": "Botão De Opção",
    "🔳": "Botão Quadrado Branco",
    "🔲": "Botão Quadrado Preto"
  }

  const description = emojiDescriptions[value];

  if (description) {
    return `(${description})`;
  } else {
    return '(emoji sem descrição)';
  }
}

// TODO: can we use this while writing emails?
document.addEventListener("input", async function(event) {
  if (event.inputType == 'deleteContentBackward') {
    return;
  }

  const isAppenderEnabled = await chrome.runtime.sendMessage('get-appender-status');

  if (!isAppenderEnabled) {
    return;
  }

  let editor = event.target;

  if (editor.getAttribute('role') == 'textbox') {
    let text = editor.innerHTML.trim();
  
    const regexWithSpan = /<span[^<>]*>(.*<img[^<>]*data-emoji[^<>]*>)+.*<\/span[^<>]*>$/;
    const regexWithoutSpan = /<img[^<>]*data-emoji[^<>]*>$/;
    let emoji = text.match(regexWithSpan) || text.match(regexWithoutSpan);

    if (emoji) {
      let emojiDescription = getEmojiDescription(emoji);
      editor.innerHTML = escapeHTMLPolicy.createHTML(text + ` <font color="#9e9e9e">${emojiDescription}</font> `);
  
      moveCursorToEndOfEditor(editor);
    }
  }
});
